# python circleci 2.0 config file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10
    
    working_directory: ~/repo

    steps:
      # obtain repo from github
      - checkout

      # create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv myenv 
            . myvenv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . myvenv/bin/activate
            flake8 --exclude=myenv --statistics
            pytest -v --cov=calculator

            
        

